import java.util.List;

/**
 * Walks the AST and emits valid Python 3 source code.
 * Bangla variable names are kept as-is (Python 3 supports Unicode identifiers).
 */
public class CodeGenerator {
    private final StringBuilder code = new StringBuilder();
    private int indentLevel = 0;

    private static final String INDENT = "    "; // 4 spaces

    // Public entry point
    public String generate(List<ASTNode> nodes) {
        code.append("# Generated by Bangla Compiler\n");
        code.append("# -*- coding: utf-8 -*-\n\n");
        for (ASTNode node : nodes) emitStatement(node);
        return code.toString();
    }

    // Statement emitter 
    private void emitStatement(ASTNode node) {
        if (node == null) return;

        if (node instanceof AssignNode) {
            AssignNode a = (AssignNode) node;
            line(a.name + " = " + emitExpr(a.expr));
        }

        else if (node instanceof IfNode) {
            IfNode ifNode = (IfNode) node;
            line("if " + emitExpr(ifNode.condition) + ":");
            indentLevel++;
            if (ifNode.thenBranch.isEmpty()) {
                line("pass");
            } else {
                for (ASTNode s : ifNode.thenBranch) emitStatement(s);
            }
            indentLevel--;

            if (ifNode.elseBranch != null && !ifNode.elseBranch.isEmpty()) {
                line("else:");
                indentLevel++;
                for (ASTNode s : ifNode.elseBranch) emitStatement(s);
                indentLevel--;
            }
        }

        else if (node instanceof PrintNode) {
            line("print(" + emitExpr(((PrintNode) node).expr) + ")");
        }
    }

    //  Expression emitter
    private String emitExpr(ASTNode node) {
        if (node instanceof NumberNode) {
            return String.valueOf(((NumberNode) node).value);
        }
        if (node instanceof StringNode) {
            // Escape backslashes and double-quotes inside the string
            String escaped = ((StringNode) node).value
                .replace("\\", "\\\\")
                .replace("\"", "\\\"");
            return "\"" + escaped + "\"";
        }
        if (node instanceof BoolNode) {
            return ((BoolNode) node).value ? "True" : "False";
        }
        if (node instanceof VarNode) {
            return ((VarNode) node).name;
        }
        if (node instanceof BinOpNode) {
            BinOpNode b = (BinOpNode) node;
            String lv = emitExpr(b.left);
            String rv = emitExpr(b.right);

            // Map Bangla/ASCII operators to Python operators
            String pyOp;
            switch (b.operator) {
                case "==": pyOp = "=="; break;
                case "!=": pyOp = "!="; break;
                case "<":  pyOp = "<";  break;
                case ">":  pyOp = ">";  break;
                case "<=": pyOp = "<="; break;
                case ">=": pyOp = ">="; break;
                default:   pyOp = b.operator; // +, -, *, / map directly
            }

            // Wrap sub-expressions in parens if they are themselves BinOpNodes
            // to preserve evaluation order exactly as parsed
            if (node instanceof BinOpNode) {
                boolean lParen = b.left  instanceof BinOpNode;
                boolean rParen = b.right instanceof BinOpNode;
                lv = lParen ? "(" + lv + ")" : lv;
                rv = rParen ? "(" + rv + ")" : rv;
            }
            return lv + " " + pyOp + " " + rv;
        }
        return "None";
    }

    // Helpers
    private void line(String text) {
        for (int i = 0; i < indentLevel; i++) code.append(INDENT);
        code.append(text).append("\n");
    }
}