# Generated by Bangla Compiler
# -*- coding: utf-8 -*-

ক = 15
খ = 4
যোগ = ক + খ
বিয়োগ = ক - খ
গুণ = ক * খ
ভাগ = ক / খ
print(যোগ)
print(বিয়োগ)
print(গুণ)
print(ভাগ)
নাম = "Shawn"
শুভেচ্ছা = "Wellcome " + নাম
print(শুভেচ্ছা)
if গুণ > 50:
    print("gunfhol 50 er besi")
else:
    print("gunfol 50 er kom")
if ক == 15:
    print("ka er value 15")
if খ != 10:
    print("Kha er value 10 na")
পাস = True
if পাস == True:
    print("passed")
else:
    print("failed")
